### ISSUE TITLE
Add support for CAfile option

### ISSUE THREAD

**Issue by mat-mo** [arusso/puppet-stunnel#16]
Some tunnels configurations require the usage of a CAfile, please add support for it.

**Comment by arusso** [comment]
I'll see about getting this added as a dedicated parameter soon. However, you should be able to specify this as a key/value in the service_opts or global_opts hash. For example:

```
$svc_opts = { 'CAfile' => '/etc/pki/tls/certs/my-ca-file' }
stunnel::tun { 'my-tunnel':
  ...
  service_opts => $svc_opts,
}
```
