### ISSUE TITLE
Globals options can be set more than once but not supported by the config

### ISSUE THREAD

**Issue by choffee** [arusso/puppet-stunnel#18]
Some global options like "socket" and "engineCtrl" can be specified more than once but the module does not support that. 

I thought that adding the option of setting a global option to an array then doing the below in the template might work. ( This is just ruby so translating it to erb first obviously.) Does that sound sane?

```ruby
global_opts = { "a"=> "b", "c"=>["d","b"]}

global_opts.sort.map do |name, value| 
    if value.kind_of?(Array)
        for val in value do
            puts name + " " + val
        end
    else
      puts name + " " + value
    end
end
```

**Comment by arusso** [comment]
As the state of the pull request may indicate, this works for me. This is a great addition, thank you!
